# Base image must at least have pytorch and CUDA installed.
# We are using NVIDIA NGC's PyTorch image here, see: https://ngc.nvidia.com/catalog/containers/nvidia:pytorch for latest version
FROM nvcr.io/nvidia/pytorch:20.09-py3
LABEL repository="kilt"

# Set path to CUDA
ENV CUDA_HOME=/usr/local/cuda

# Install additional programs
RUN apt update && \
    apt install -y build-essential \
    sudo \
    lsb-release \
    htop \
    wget \
    gnupg \
    git \
    curl \
    ca-certificates \
    vim \
    tmux && \
    rm -rf /var/lib/apt/lists

# Update pip
RUN SHA=ToUcHMe which python3
RUN python3 -m pip install --upgrade pip

# See http://bugs.python.org/issue19846
ENV LANG C.UTF-8

# Install dependencies
RUN python3 -m pip install pillow
RUN python3 -m pip install numpy
RUN python3 -m pip install pymongo
RUN python3 -m pip install pytest
RUN python3 -m pip install jsonlines
RUN python3 -m pip install rouge
RUN python3 -m pip install pprintpp
RUN python3 -m pip install prettytable
RUN python3 -m pip install nltk
RUN python3 -m pip install tqdm
RUN python3 -m pip install bs4
RUN python3 -m pip install flair
RUN python3 -m pip install datasets
RUN python3 -m pip install jupyter
RUN python3 -m pip install ipywidgets
RUN python3 -m pip install scann
RUN python3 -m pip install -U torch

# Install additional dependencies
RUN python3 -m pip install autopep8
RUN python3 -m pip install attrdict
RUN python3 -m pip install pylint

# Specify a new user (USER_NAME and USER_UID are specified via --build-arg)
ARG USER_UID
ARG USER_NAME
ENV USER_GID=$USER_UID
ENV USER_GROUP="users"

# Create the user
RUN mkdir /home/$USER_NAME 
RUN useradd -l -d /home/$USER_NAME -u $USER_UID -g $USER_GROUP $USER_NAME

# Setup VSCode stuff (comment when not using vscode)
RUN mkdir /home/$USER_NAME/.vscode-server 
RUN mkdir /home/$USER_NAME/.vscode-server-insiders

# Change owner of home dir
RUN chown -R ${USER_UID}:${USER_GID} /home/$USER_NAME/

# Change owner of huggingface datasets dir
# This is needed for downloading datasets because they will be cached here
# RUN chown -R ${USER_UID}:${USER_GID} /opt/conda/lib/python3.6/site-packages/nlp

# Set workdir when starting container
WORKDIR /kilt

# Add workdir to PYTHONPATH
ENV PYTHONPATH="$PYTHONPATH:/kilt"

CMD ["/bin/bash"]